---
version: 0.2
phases:
  install:
    commands:
      - kubectl version --short --client
  pre_build:
      commands:
        - TAG="${BRANCH}-$CODEBUILD_BUILD_NUMBER.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i.bak -e 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' -e 's@CLIENT_IMAGE@'"$REPOSITORY_URI/client:$TAG"'@' kubernetes/k8-deployment.yaml
        - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
        - echo "${BRANCH}"
        - |
          if expr "${BRANCH}" : ".*dev" >/dev/null; then
            sed -i.bak -e 's@NAMESPACE@'"reciter"'@' -e 's@APPNAME@'"reciter-pm-dev"'@' -e 's@HPANAME@'"hpa-reciter-pm-dev"'@' -e 's@ENVIRONMENT_LABEL@'"dev"'@' kubernetes/k8-deployment.yaml;
          fi
        - |
          if expr "${BRANCH}" : ".*master" >/dev/null; then
            sed -i.bak -e 's@NAMESPACE@'"reciter"'@' -e 's@APPNAME@'"reciter-pm-prod"'@' -e 's@HPANAME@'"hpa-reciter-pm-prod"'@' -e 's@ENVIRONMENT_LABEL@'"prod"'@' kubernetes/k8-deployment.yaml;
          fi
        - $(aws ecr get-login --no-include-email)
        - cat ./kubernetes/k8-deployment.yaml
        - mv config/local.example.js config/local.js
        - sed -i -e "s/ADMIN_API_KEY/$ADMIN_API_KEY/g" config/local.js
        - sed -i -e "s/TOKEN_SECRET/$TOKEN_SECRET/g" config/local.js
        #Install Trivy for container and dependency scanning
        - apt-get install wget apt-transport-https gnupg lsb-release
        - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        - echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
        - apt-get update
        - apt-get install -y trivy
  build:
    commands:
      - |
        if expr "${BRANCH}" : ".*master" >/dev/null || expr "${BRANCH}" : ".*dev" >/dev/null; then
          docker build --tag $REPOSITORY_URI:$TAG .
          docker build --tag $REPOSITORY_URI/client:$TAG ./client
        fi


  post_build:
    commands:
      - |
        if expr "${BRANCH}" : ".*master" >/dev/null || expr "${BRANCH}" : ".*dev" >/dev/null; then
          trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL $REPOSITORY_URI:$TAG
          docker push $REPOSITORY_URI:$TAG
          trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL $REPOSITORY_URI/client:$TAG
          docker push $REPOSITORY_URI/client:$TAG
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region us-east-1 --role-arn $EKS_KUBECTL_ROLE_ARN
          kubectl apply -f ./kubernetes/k8-deployment.yaml
          printf '[{"name":"k8-deployment.yaml","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
        fi
