apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: reciter-pm
  namespace: NAMESPACE
  labels:
    app: reciter-pm
    ENVIRONMENT_LABEL
    tier: frontend
    owner: szd2013
spec:
  selector:
    matchLabels:
      app: reciter-pm
      tier: frontend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: reciter-pm
        tier: frontend
        ENVIRONMENT_LABEL
        owner: szd2013
    spec:
      containers:
      - image: CONTAINER_IMAGE
        name: reciter-pm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: reciter-pm
        resources:
          requests:
            memory: 1500m
            cpu: 0.7
          limits:
            memory: 2G
            cpu: 0.8
      - image: CLIENT_IMAGE
        name:  reciter-pm-client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 350Mi
        livenessProbe:
          httpGet:
            path: "/nginx-health"
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/nginx-health"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 1
          timeoutSeconds: 1
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reciter-pm
  namespace: reciter
  labels:
    app: reciter-pm
    environment: ENVIRONMENT_LABEL
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reciter-pm
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
